#!/usr/bin/python3.7

import os
import json

# Some of the libraries supplied by MATLAB runtime are old and runtime prioritize them over system libraries. So we rename them and make runtime use the system libraries instead
os.system("mv /usr/local/MATLAB/MATLAB_Runtime/v97/bin/glnxa64/libexpat.so.1 /usr/local/MATLAB/MATLAB_Runtime/v97/bin/glnxa64/libexpat.so.1-appended")
os.system("mv /usr/local/MATLAB/MATLAB_Runtime/v97/bin/glnxa64/libtiff.so.5 /usr/local/MATLAB/MATLAB_Runtime/v97/bin/glnxa64/libtiff.so.5-appended")

# Print the system specs in the log file
os.system('cat /proc/cpuinfo')

# Set initial Flywheel paths
flywheel_base ='/flywheel/v0/'
manifest_file = os.path.join(flywheel_base, 'manifest.json')
config_path = os.path.join(flywheel_base, 'config.json')
first_output_dir = '/firstOutput' # Working in the flywheel output folder might cause issues so creating a first level output folder 
os.system('mkdir %s'%first_output_dir)
final_output_dir = os.path.join(flywheel_base, 'output')

# Set paths to the functions
matlab_func = '/opt/func_input/run_mainWrapper.sh'
externalMGZMakerPath = '/opt/make_fsaverage.py'
externalMapGifMakerPath = '/opt/plot_maps.py'
externalSurfaceMakerPath = '/opt/plot_surface.py'
externalHtmlMakerPath = '/opt/ldog_make_html.py'

# Set paths to the tools 
mcr_path = '/usr/local/MATLAB/MATLAB_Runtime/v97' #path to MATLAB runtime
workbench_path = '/usr/bin/wb_command'

###################Parse Config Here###########################################

with open(config_path) as config_file:
    job_config = json.load(config_file)
config = job_config['config']

dataFileType = config['dataFileType']
dataSourceType = config['dataSourceType']
trimDummyStimTRs = config['trimDummyStimTRs']
averageAcquisitions = config['averageAcquisitions']
tr = config['tr']
modelClass = config['modelClass']
averageVoxels = config['averageVoxels']
modelOpts = '{' + config['modelOpts'] + '}'

################### Input Files ###############################################

# Path to input folders 
func_zip_folder01 = os.path.join(flywheel_base, 'input/funcZip01')
func_zip_folder02 = os.path.join(flywheel_base, 'input/funcZip02')
func_zip_folder03 = os.path.join(flywheel_base, 'input/funcZip03')
func_zip_folder04 = os.path.join(flywheel_base, 'input/funcZip04')
func_zip_folder05 = os.path.join(flywheel_base, 'input/funcZip05')
func_zip_folder06 = os.path.join(flywheel_base, 'input/funcZip06')
func_zip_folder07 = os.path.join(flywheel_base, 'input/funcZip07')
func_zip_folder08 = os.path.join(flywheel_base, 'input/funcZip08')
func_zip_folder09 = os.path.join(flywheel_base, 'input/funcZip09')
func_zip_folder10 = os.path.join(flywheel_base, 'input/funcZip10')
stim_file_folder = os.path.join(flywheel_base, 'input/stimFile')
struct_zip_folder = os.path.join(flywheel_base, 'input/structZip')
mask_file_folder = os.path.join(flywheel_base, 'input/maskFile')
payload_file_folder = os.path.join(flywheel_base, 'input/payloadFile')

# Path to required inputs
func_zip_path01 = os.path.join(func_zip_folder01, os.listdir(func_zip_folder01)[0])
stim_file_path = os.path.join(stim_file_folder, os.listdir(stim_file_folder)[0])
struct_zip_path = os.path.join(struct_zip_folder, os.listdir(struct_zip_folder)[0])

# Path to optional inputs   
if os.path.isdir(func_zip_folder02) == True:    
    func_zip_path02 = os.path.join(func_zip_folder02, os.listdir(func_zip_folder02)[0])
else:
    func_zip_path02 = 'Na'
if os.path.isdir(func_zip_folder03) == True:    
    func_zip_path03 = os.path.join(func_zip_folder03, os.listdir(func_zip_folder03)[0])
else:
    func_zip_path03 = 'Na'
if os.path.isdir(func_zip_folder04) == True:    
    func_zip_path04 = os.path.join(func_zip_folder04, os.listdir(func_zip_folder04)[0])
else:
    func_zip_path04 = 'Na'
if os.path.isdir(func_zip_folder05) == True:    
    func_zip_path05 = os.path.join(func_zip_folder05, os.listdir(func_zip_folder05)[0])
else:
    func_zip_path05 = 'Na'
if os.path.isdir(func_zip_folder06) == True:    
    func_zip_path06 = os.path.join(func_zip_folder06, os.listdir(func_zip_folder06)[0])
else:
    func_zip_path06 = 'Na'
if os.path.isdir(func_zip_folder07) == True:    
    func_zip_path07 = os.path.join(func_zip_folder07, os.listdir(func_zip_folder07)[0])
else:
    func_zip_path07 = 'Na'
if os.path.isdir(func_zip_folder08) == True:    
    func_zip_path08 = os.path.join(func_zip_folder08, os.listdir(func_zip_folder08)[0])
else:
    func_zip_path08 = 'Na'
if os.path.isdir(func_zip_folder09) == True:    
    func_zip_path09 = os.path.join(func_zip_folder09, os.listdir(func_zip_folder09)[0])
else:
    func_zip_path09 = 'Na'
if os.path.isdir(func_zip_folder10) == True:    
    func_zip_path10 = os.path.join(func_zip_folder10, os.listdir(func_zip_folder10)[0])
else:
    func_zip_path10 = 'Na'
if os.path.isdir(mask_file_folder) == True:    
    mask_file_path = os.path.join(mask_file_folder, os.listdir(mask_file_folder)[0])
else:
    mask_file_path = 'Na'
if os.path.isdir(payload_file_folder) == True:    
    payload_file_path = os.path.join(mask_file_folder, os.listdir(payload_file_folder)[0])
else:
    payload_file_path = 'Na'


if dataSourceType == 'icafix':
    # Create a folder for hcpstruct config
    hcpconfpath = '/opt/hcpconf'
    os.system('mkdir %s' % hcpconfpath)
    
    # Extract the hcp config into the configfolder
    os.system('unzip -j %s \'*/*.json\' -d %s' % (struct_zip_path, hcpconfpath))
    
    hcpconfig = os.path.join(hcpconfpath, os.listdir(hcpconfpath)[0])
    with open(hcpconfig) as hcpconf:
        job_config2 = json.load(hcpconf)
    config2 = job_config2['config']
    
    subject_id = config2['Subject']
    RegName = config2['RegName']

elif dataSourceType == 'ldogfix':  
    # Create a folder for ldog subject text file
    subjecttext = '/tmp/subjectPathFolder'
    os.system('mkdir %s' % subjecttext)
    os.system('unzip -j %s \'subject_id.txt\' -d %s' % (struct_zip_path, subjecttext))
    textfile = os.path.join(subjecttext, os.listdir(subjecttext)[0])
    with open (textfile, 'r') as idfile:
        subject_id = idfile.readlines()[0]
    RegName = 'Na'
   
    # Set paths to the surface items (mesh, calculations, etc.) and unzip
    ldogSurfaceAndCalculations = '/tmp/surface_items' #ldog_surface_calculations_folder
    os.system('mkdir %s' % ldogSurfaceAndCalculations)
    os.system('unzip -j %s Atlas/exvivo_warp_files.zip -d %s' % (struct_zip_path, ldogSurfaceAndCalculations))
    os.system('unzip -j %s Atlas/Woofsurfer.zip -d %s' % (struct_zip_path, ldogSurfaceAndCalculations))    
    os.system('unzip -q %s/Woofsurfer.zip -d %s/' % (ldogSurfaceAndCalculations, ldogSurfaceAndCalculations))
    os.system('unzip -q %s/exvivo_warp_files.zip -d %s/' % (ldogSurfaceAndCalculations, ldogSurfaceAndCalculations))    

######################### Run Algorithm #######################################
    
cmd = """%s %s -mcruserdata ParallelProfile:/usr/flywheel.mlsettings '%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s' 'maskFilePath' '%s' \
'payloadPath' '%s' 'dataFileType' '%s' 'dataSourceType' '%s' \
'trimDummyStimTRs' '%s' 'averageAcquisitions' '%s' 'tr' '%s' \
'externalMGZMakerPath' '%s' 'RegName' '%s' 'modelClass' '%s' 'modelOpts' '%s' \
'workbenchPath' '%s' 'outPath' '%s' 'flywheelFlag' '1' 'Subject' '%s' 'averageVoxels' '%s' externalMapGifMakerPath '%s' externalSurfaceMakerPath '%s' \
'externalHtmlMakerPath' '%s' ldogSurfaceAndCalculations '%s'""" % (matlab_func, mcr_path, func_zip_path01, func_zip_path02, func_zip_path03, func_zip_path04, func_zip_path05, 
                                                                   func_zip_path06, func_zip_path07, func_zip_path08, func_zip_path09, func_zip_path10, stim_file_path, 
                                                                   struct_zip_path, mask_file_path, payload_file_path, dataFileType, dataSourceType, trimDummyStimTRs, 
                                                                   averageAcquisitions, tr, externalMGZMakerPath, RegName, modelClass, modelOpts, workbench_path, first_output_dir, 
                                                                   subject_id, averageVoxels, externalMapGifMakerPath, externalSurfaceMakerPath, externalHtmlMakerPath, ldogSurfaceAndCalculations)

os.system(cmd)        

################### Zip everything and output #################################

# Move mat and pdf to the final output directory
for i in os.listdir(first_output_dir):
    if os.path.splitext(i)[-1].lower() == '.mat' or os.path.splitext(i)[-1].lower() == '.pdf':
        os.system('mv %s %s/'%(os.path.join(first_output_dir, i), final_output_dir)) 
 
# Move the folders containing any mri image files to the final output     
if os.path.exists((os.path.join(first_output_dir,'%s_maps_cifti' % subject_id))):
    os.system('cd %s; zip -q -r %s *'%(os.path.join(first_output_dir,'%s_maps_cifti' % subject_id), os.path.join(final_output_dir,'%s_maps_cifti.zip' % subject_id)))
if os.path.exists((os.path.join(first_output_dir,'%s_maps_nativeMGZ' % subject_id))):
    os.system('cd %s; zip -q -r %s *'%(os.path.join(first_output_dir,'%s_maps_nativeMGZ' % subject_id), os.path.join(final_output_dir,'%s_maps_nativeMGZ.zip' % subject_id)))
if os.path.exists((os.path.join(first_output_dir,'%s_maps_nativeMGZ_pseudoHemisphere' % subject_id))):    
    os.system('cd %s; zip -q -r %s *'%(os.path.join(first_output_dir,'%s_maps_nativeMGZ_pseudoHemisphere' % subject_id), os.path.join(final_output_dir,'%s_maps_nativeMGZ_pseudoHemisphere.zip' % subject_id)))
if os.path.exists((os.path.join(first_output_dir,'%s_maps_volumetric' % subject_id))):
    os.system('cd %s; zip -q -r %s *'%(os.path.join(first_output_dir,'%s_maps_volumetric' % subject_id), os.path.join(final_output_dir,'%s_maps_volumetric.zip' % subject_id)))

# If the icafix protocol is used, move the brain plots directly to the final output folder     
if dataSourceType == 'icafix':
    for i in os.listdir(first_output_dir):
        if os.path.splitext(i)[-1].lower() == '.png':
            os.system('mv %s %s/'%(os.path.join(first_output_dir, i), final_output_dir))

# If ldog protocol is used create an html from the brain plots
if dataSourceType == 'ldogfix':   
    images_folder = os.path.join(first_output_dir, 'images')
    os.system('mkdir %s' % images_folder)
    os.system('cd %s; mv *.png *.gif %s' % (first_output_dir, images_folder))    
    os.system('cd %s; zip -q -r %s images *.html' % (first_output_dir, os.path.join(final_output_dir, subject_id + '_results.html.zip')))
